#!/bin/sh
function join { local IFS="$1"; shift; echo "$*"; }

_libs=(
  "$(hab pkg path core/gcc-libs)/lib" \
  "$(hab pkg path uafgina/imagemagick)/lib" \
  "$(hab pkg path uafgina/libtiff)/lib" \
  "$(hab pkg path ssd/libjpeg)/lib" \
  "$(hab pkg path core/libpng)/lib" \
  "$(hab pkg path core/zlib)/lib"
)

export LD_LIBRARY_PATH=$(join : ${_libs[@]})
export FEEDER_HOME="{{pkg.path}}"
export FEEDER_DATA="{{pkg.svc_data_path}}"

echo "Creating var/run"
mkdir -p {{pkg.svc_var_path}}/run
chown hab:hab {{pkg.svc_var_path}}/run

echo "Removing previous version deployed at ${FEEDER_DATA}"
rm -rf ${FEEDER_DATA}/dist

echo "Deploying new version from ${FEEDER_HOME} to ${FEEDER_DATA}"
cp -a ${FEEDER_HOME}/dist ${FEEDER_DATA}/dist

echo "Linking database.yml"
ln -sf {{pkg.svc_config_path}}/database.yml ${FEEDER_DATA}/dist/config/database.yml
echo "Linking sidekiq.yml"
ln -sf {{pkg.svc_config_path}}/sidekiq.yml ${FEEDER_DATA}/dist/config/sidekiq.yml
echo "Linking secrets.yml"
ln -sf {{pkg.svc_config_path}}/secrets.yml ${FEEDER_DATA}/dist/config/secrets.yml
echo "Linking puma.rb"
ln -sf {{pkg.svc_config_path}}/puma.rb ${FEEDER_DATA}/dist/config/puma.rb
echo "Linking initializers/sidekiq.rb"
ln -sf {{pkg.svc_config_path}}/sidekiq.rb ${FEEDER_DATA}/dist/config/initializers/sidekiq.rb
echo "Linking cache path"
ln -sf {{cfg.cache_path}} ${FEEDER_DATA}/dist/public/uploads
ln -sf {{cfg.cache_path}} ${FEEDER_DATA}/dist/public/dragonfly

export GEM_HOME="${FEEDER_DATA}/dist/vendor/bundle/ruby/2.3.0"
export GEM_PATH="$(hab pkg path core/ruby)/lib/ruby/gems/2.3.0:$(hab pkg path core/bundler):$GEM_HOME"
export PATH="$PATH:${FEEDER_DATA}/dist/bin:$(hab pkg path uafgina/imagemagick)/bin"
export RAILS_ENV="production"

chown -R hab:hab ${FEEDER_DATA}/dist
chmod go+x ${FEEDER_DATA}
mkdir -p {{pkg.svc_var_path}}/log
chown -R hab:hab {{pkg.svc_var_path}}/log

cd ${FEEDER_DATA}/dist

exec 2>&1

if [[ ! -f ${FEEDER_DATA}/.migrations_complete ]]; then
  echo "Running 'rake db:create && rake db:migrate' in ${PWD}"
  exec bin/rake db:migrate && \
       touch $FEEDER_DATA/.migrations_complete
fi