production:
  solr:
{{~#if bind.has_solr}}
  hostname: {{bind.solr.ip}}
  port: {{bind.solr.port}}
{{~else}}
  hostname: {{cfg.solr.hostname}}
  port: {{cfg.solr.port}}
{{~/if}}
  log_level: WARNING

