production:
  solr:
    hostname: <%= ENV['SOLR_HOSTNAME'] %>
    port: <%= ENV['SOLR_PORT'] || 8983 %>
    log_level: WARNING
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8984
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
