---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  attributes:
    puffin:
      account: vagrant
      database:
        password: 'puffinpostgres'
    chruby:
      default: embedded
      auto_switch: false
    postgresql:
      password:
        postgres: 'postgresuserpassword'

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[puffin::default]
    attributes:
